"""
WAF Detection v2 — P5: expanded signatures, confidence scores, evidence.
Standalone module imported by tech_detect.
"""
from __future__ import annotations
import re
from dataclasses import dataclass, field

@dataclass
class WAFResult:
    name: str
    confidence: int          # 0-100
    evidence: list[str] = field(default_factory=list)
    detection_methods: list[str] = field(default_factory=list)

# (waf_name, [(pattern, source, confidence_contribution, method)])
# source: "header" | "cookie" | "body" | "status"
WAF_RULES: list[tuple[str, list[tuple[str, str, int, str]]]] = [
    ("Cloudflare", [
        (r"cf-ray",                    "header", 90, "header"),
        (r"cloudflare",                "header", 70, "header"),
        (r"cf_clearance",              "cookie", 85, "cookie"),
        (r"__cfduid",                  "cookie", 80, "cookie"),
        (r"cloudflare",                "body",   50, "body"),
        (r"Attention Required.*Cloudflare", "body", 95, "error_page"),
    ]),
    ("Akamai", [
        (r"akamai",                    "header", 80, "header"),
        (r"ak_bmsc",                   "cookie", 90, "cookie"),
        (r"akamaighost",               "header", 95, "header"),
        (r"x-akamai-transformed",      "header", 95, "header"),
        (r"x-check-cacheable",         "header", 70, "header"),
    ]),
    ("Imperva / Incapsula", [
        (r"incapsula",                 "header", 90, "header"),
        (r"visid_incap",               "cookie", 95, "cookie"),
        (r"incap_ses",                 "cookie", 95, "cookie"),
        (r"x-iinfo",                   "header", 85, "header"),
        (r"_incap_",                   "cookie", 80, "cookie"),
    ]),
    ("AWS WAF", [
        (r"awswaf",                    "header", 90, "header"),
        (r"x-amzn-waf",                "header", 95, "header"),
        (r"x-amzn-requestid",          "header", 40, "header"),
        (r"aws-waf-token",             "cookie", 95, "cookie"),
    ]),
    ("Azure Front Door", [
        (r"x-azure-ref",               "header", 95, "header"),
        (r"x-fd-healthprobe",          "header", 90, "header"),
        (r"x-ms-ref",                  "header", 85, "header"),
    ]),
    ("Fastly", [
        (r"x-served-by.*cache",        "header", 80, "header"),
        (r"fastly",                    "header", 75, "header"),
        (r"x-fastly-request-id",       "header", 95, "header"),
        (r"x-cache.*HIT.*fastly",      "header", 85, "header"),
    ]),
    ("Sucuri", [
        (r"x-sucuri-id",               "header", 95, "header"),
        (r"sucuri",                    "header", 80, "header"),
        (r"x-sucuri-cache",            "header", 90, "header"),
        (r"Access Denied.*Sucuri",     "body",   95, "error_page"),
    ]),
    ("F5 BIG-IP", [
        (r"bigipserver",               "cookie", 90, "cookie"),
        (r"f5-trafficshield",          "header", 95, "header"),
        (r"ts[a-f0-9]{8}=",            "cookie", 85, "cookie"),
        (r"x-wa-info",                 "header", 80, "header"),
    ]),
    ("ModSecurity", [
        (r"mod_security",              "header", 90, "header"),
        (r"modsecurity",               "header", 90, "header"),
        (r"NOYB",                      "header", 70, "header"),
        (r"mod_security",              "body",   85, "error_page"),
    ]),
    ("Radware", [
        (r"x-sl-compstate",            "header", 90, "header"),
        (r"rdwr",                      "cookie", 85, "cookie"),
        (r"radware",                   "header", 80, "header"),
    ]),
    ("Wordfence", [
        (r"wordfence",                 "body",   90, "body"),
        (r"wfwaf-authcookie",          "cookie", 95, "cookie"),
        (r"generated by Wordfence",    "body",   95, "error_page"),
    ]),
    ("Fortinet", [
        (r"fortigate",                 "header", 90, "header"),
        (r"fortiwebcookie",            "cookie", 95, "cookie"),
        (r"FORTIWAFSID",               "cookie", 95, "cookie"),
    ]),
    ("Barracuda", [
        (r"barra_counter_session",     "cookie", 90, "cookie"),
        (r"barracuda",                 "header", 80, "header"),
        (r"barracuda_",                "cookie", 85, "cookie"),
    ]),
]


def detect_wafs(html: str, headers: dict, cookies: str = "") -> list[WAFResult]:
    """
    Detect WAFs from response headers, cookies, and body.
    Returns list of WAFResult with confidence scores and evidence.
    Debug info attached as module-level attributes after call:
      detect_wafs.signatures_checked — total signature rules evaluated
      detect_wafs.matched_count      — number of WAFs matched (≥70% confidence)
    """
    # Lowercase the joined header string — WAF patterns are lowercase, servers vary
    header_str = " ".join(f"{k.lower()}: {v.lower()}" for k, v in headers.items())
    body_sample = html[:30000]
    results: list[WAFResult] = []
    signatures_checked = 0

    for waf_name, rules in WAF_RULES:
        matched_confidence = 0
        evidence: list[str] = []
        methods: list[str] = []

        for pattern, source, contrib, method in rules:
            signatures_checked += 1
            target = (header_str if source == "header"
                      else cookies if source == "cookie"
                      else body_sample)
            m = re.search(pattern, target, re.IGNORECASE)
            if m:
                matched_confidence = max(matched_confidence, contrib)
                snippet = m.group(0)[:60]
                evidence.append(f"[{method}] {snippet}")
                if method not in methods:
                    methods.append(method)

        if matched_confidence >= 70:
            results.append(WAFResult(
                name=waf_name,
                confidence=matched_confidence,
                evidence=evidence,
                detection_methods=methods,
            ))

    # Attach debug stats as function attributes for callers to inspect
    detect_wafs.signatures_checked = signatures_checked
    detect_wafs.matched_count = len(results)

    import logging
    logging.getLogger("waf_detect").debug(
        f"[waf_detect] signatures_checked={signatures_checked} "
        f"matched_count={len(results)} "
        f"detected={[w.name for w in results] or 'none'}"
    )
    return results


# Initialise debug attributes so they're always accessible
detect_wafs.signatures_checked = 0  # type: ignore[attr-defined]
detect_wafs.matched_count = 0       # type: ignore[attr-defined]
